name: Ceedling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    # Install ceedling
    - name: Install Ceedling
      run: gem install ceedling

    # Runs a set of commands using the runners shell
    - name: Test
      run: ceedling test:all